"""Render a split-screen comparison of BiRRT vs trajectory-optimized paths.

Requires a debug pickle with stage trajectories (generated by setting
CAPTURE_STAGE_TRAJECTORIES = True and replanning).

For unconstrained legs (reach_approach, home), the stage trajectories are in
23-D active-joint space and can be rendered directly.

Usage:
    .venv/bin/python scripts/video/render_rrt_vs_trajopt.py
    .venv/bin/python scripts/video/render_rrt_vs_trajopt.py --index 0 --leg reach_approach
"""

import argparse
import os
import pickle
import subprocess
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from pydrake.all import (ClippingRange, ColorRenderCamera, CameraInfo,
                         MakeRenderEngineVtk, RenderCameraCore,
                         RenderEngineVtkParams, RigidTransform,
                         RollPitchYaw, RotationMatrix)

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "src"))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import common
import plan_grid as E
from rby1_planning import Rby1ActiveJointLayout, make_default_rby1_infrastructure

RENDERER = "vtk"
HALF_W, FULL_H = 960, 1080
FPS = 30

CAM_POS = np.array([2.40, 0.20, 1.10])
CAM_LOOK_AT = np.array([0.30, -0.20, 0.55])
CAM_FOV_Y = 0.90

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT_DIR = os.path.join(REPO, "video")

LEG_SCENE = {
    "reach_approach": "open_box",
    "reach_descend": "open_box",
    "lift": "held",
    "place": "held",
    "home_retreat": "placed",
    "home": "placed",
}


def _look_at(eye, target, up=np.array([0.0, 0.0, 1.0])):
    forward = target - eye
    forward = forward / np.linalg.norm(forward)
    right = np.cross(-up, forward)
    right = right / np.linalg.norm(right)
    down = np.cross(forward, right)
    R = np.column_stack([right, down, forward])
    return RigidTransform(RotationMatrix(R), eye)


def make_camera():
    core = RenderCameraCore(
        RENDERER,
        CameraInfo(HALF_W, FULL_H, CAM_FOV_Y),
        ClippingRange(0.05, 20.0),
        RigidTransform(),
    )
    return ColorRenderCamera(core, show_window=False)


def build_scene(kind, bx, by, placed_box_pose):
    if kind == "open_box":
        obstacles = [E.TABLE] + E.open_box_walls(E.box_pose_for(bx, by))
        plant, checker, diagram = make_default_rby1_infrastructure(
            obstacles=obstacles, open_grippers=True)
    elif kind == "held":
        from rby1_planning import HeldBox
        held = HeldBox(hand=E.HAND, size=E.SIZE, offset=E.OFFSET, rpy=E.RPY,
                       visual=True, open_top=True, wall_thickness=E.WALL_T,
                       wall_height=E.WALL_HEIGHT)
        plant, checker, diagram = make_default_rby1_infrastructure(
            held_boxes=held, obstacles=E.TABLE)
    elif kind == "placed":
        obstacles = [E.TABLE] + E.open_box_walls(placed_box_pose, prefix="placed")
        plant, checker, diagram = make_default_rby1_infrastructure(
            obstacles=obstacles, open_grippers=True)
    else:
        raise ValueError(kind)
    return plant, checker, diagram, Rby1ActiveJointLayout(plant)


def add_renderer(diagram):
    sg = diagram.GetSubsystemByName("scene_graph")
    if not sg.HasRenderer(RENDERER):
        sg.AddRenderer(RENDERER, MakeRenderEngineVtk(RenderEngineVtkParams()))
    return sg


def get_font(size):
    for p in ("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",):
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def render_trajectory(qs, plant, diagram, layout, sg, camera, X_WC):
    """Render all configurations into a list of PIL images."""
    frames = []
    ctx = diagram.CreateDefaultContext()
    pctx = plant.GetMyContextFromRoot(ctx)
    sg_ctx = sg.GetMyContextFromRoot(ctx)

    for q23 in qs:
        q_full = plant.GetPositions(pctx)
        q_full[layout.plant_idxs] = q23
        plant.SetPositions(pctx, q_full)
        qobj = sg.get_query_output_port().Eval(sg_ctx)
        img = qobj.RenderColorImage(camera, sg.world_frame_id(), X_WC)
        arr = np.asarray(img.data).reshape(FULL_H, HALF_W, 4)[:, :, :3]
        frames.append(Image.fromarray(arr.copy()))
    return frames


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cache-dir", default=E.DEFAULT_CACHE_DIR)
    ap.add_argument("--index", type=int, default=0)
    ap.add_argument("--leg", default=None,
                    help="Which leg to show (default: auto-pick best unconstrained)")
    ap.add_argument("--output", default=os.path.join(OUT_DIR, "rrt_vs_trajopt.mp4"))
    args = ap.parse_args()

    # Load debug pickle
    debug_path = os.path.join(args.cache_dir, f"point_{args.index:02d}_debug.pkl")
    if not os.path.exists(debug_path):
        print(f"No debug pickle at {debug_path}")
        sys.exit(1)

    with open(debug_path, "rb") as f:
        debug = pickle.load(f)

    # Load the main plan for box coordinates
    from plan_format.plan_io import load_plan
    plan_path = E.cache_path_for(args.cache_dir, args.index)
    _, meta = load_plan(plan_path)
    bx, by = meta["bx"], meta["by"]

    # Stages are nested: debug['debug'][leg_name]['stages']
    debug_legs = debug.get("debug", {})
    if not debug_legs:
        print("No debug leg data in pickle.")
        sys.exit(1)

    # Pick the best leg for comparison
    target_leg = args.leg
    if target_leg is None:
        for candidate in ("reach_approach", "home", "reach_descend", "home_retreat"):
            if candidate in debug_legs:
                leg_stages = debug_legs[candidate].get("stages", {})
                has_rrt = (leg_stages.get("rrt_shortcut") is not None or
                           leg_stages.get("rrt_raw") is not None)
                has_opt = leg_stages.get("trajopt") is not None
                if has_rrt and has_opt:
                    target_leg = candidate
                    break
    if target_leg is None:
        print(f"No suitable leg found. Available: {list(debug_legs.keys())}")
        sys.exit(1)

    print(f"Using leg: {target_leg}")
    leg_stages = debug_legs[target_leg].get("stages", {})

    # Use rrt_raw for maximum visual contrast, fall back to rrt_shortcut
    rrt_data = leg_stages.get("rrt_raw") or leg_stages.get("rrt_shortcut")
    # Use trajopt (23-D) rather than toppra (29-D) for matching dimensionality
    opt_data = leg_stages.get("trajopt")

    if rrt_data is None or opt_data is None:
        print(f"Missing stage data for {target_leg}: "
              f"rrt_shortcut={'ok' if rrt_data else 'None'}, "
              f"toppra={'ok' if opt_data else 'None'}")
        sys.exit(1)

    rrt_qs = rrt_data["q"]
    opt_qs = opt_data["q"]
    print(f"  RRT shortcut: {len(rrt_qs)} configs")
    print(f"  TOPPRA (final): {len(opt_qs)} configs")

    # Compute placed box pose
    placed_pose = E.box_pose_for(bx, by)
    place_leg = next((l for l in meta["legs"] if l["name"] == "place"), None)
    if place_leg is not None:
        plant_h, _, diagram_h, layout_h = build_scene("held", bx, by, placed_pose)
        ctx = diagram_h.CreateDefaultContext()
        pctx = plant_h.GetMyContextFromRoot(ctx)
        q_full = plant_h.GetPositions(pctx)
        q_full[layout_h.plant_idxs] = place_leg["q"][-1]
        plant_h.SetPositions(pctx, q_full)
        ee = plant_h.GetBodyByName(f"ee_{E.HAND}",
                                   plant_h.GetModelInstanceByName(f"{E.HAND}_arm"))
        placed_pose = (plant_h.EvalBodyPoseInWorld(pctx, ee)
                       @ RigidTransform(RollPitchYaw(E.RPY), E.OFFSET))

    # Build scene for this leg
    kind = LEG_SCENE.get(target_leg, "open_box")
    plant, checker, diagram, layout = build_scene(kind, bx, by, placed_pose)
    sg = add_renderer(diagram)
    camera = make_camera()
    X_WC = _look_at(CAM_POS, CAM_LOOK_AT)

    # Match frame counts: resample to the longer trajectory's count
    n_frames = max(len(rrt_qs), len(opt_qs))
    # Cap at 10 seconds of video
    max_frames = FPS * 12
    stride = max(1, n_frames // max_frames)

    rrt_sampled = rrt_qs[::stride]
    opt_sampled = opt_qs[::stride]

    # Pad shorter one by repeating last frame
    target_len = max(len(rrt_sampled), len(opt_sampled))
    if len(rrt_sampled) < target_len:
        pad = np.tile(rrt_sampled[-1:], (target_len - len(rrt_sampled), 1))
        rrt_sampled = np.vstack([rrt_sampled, pad])
    if len(opt_sampled) < target_len:
        pad = np.tile(opt_sampled[-1:], (target_len - len(opt_sampled), 1))
        opt_sampled = np.vstack([opt_sampled, pad])

    print(f"  Rendering {target_len} frames per panel...")

    # Render both trajectories
    print("  Rendering RRT panel...")
    rrt_frames = render_trajectory(rrt_sampled, plant, diagram, layout, sg, camera, X_WC)
    print("  Rendering optimized panel...")
    opt_frames = render_trajectory(opt_sampled, plant, diagram, layout, sg, camera, X_WC)

    # Compose side-by-side with labels
    font = get_font(24)
    small_font = get_font(18)

    full_w = HALF_W * 2  # 1920

    def compose_frame(rrt_pil, opt_pil, frame_idx):
        combined = Image.new("RGB", (full_w, FULL_H), (26, 26, 46))
        combined.paste(rrt_pil, (0, 0))
        combined.paste(opt_pil, (HALF_W, 0))

        draw = ImageDraw.Draw(combined)
        # Divider line
        draw.line([(HALF_W, 0), (HALF_W, FULL_H)], fill=(100, 100, 100), width=2)

        # Labels at top
        draw.rectangle([0, 0, HALF_W, 40], fill=(0, 0, 0, 180))
        draw.rectangle([HALF_W, 0, full_w, 40], fill=(0, 0, 0, 180))
        draw.text((10, 8), "BiRRT + Shortcutting", font=font, fill=(255, 213, 79))
        draw.text((HALF_W + 10, 8), "After Trajectory Optimization", font=font,
                  fill=(102, 187, 106))

        # Frame counter
        draw.text((10, FULL_H - 30), f"Frame {frame_idx+1}/{target_len}",
                  font=small_font, fill=(160, 160, 160))

        return combined

    # Encode to MP4
    os.makedirs(OUT_DIR, exist_ok=True)
    cmd = [
        "ffmpeg", "-y",
        "-f", "rawvideo", "-pix_fmt", "rgb24",
        "-s", f"{full_w}x{FULL_H}", "-r", str(FPS),
        "-i", "pipe:0",
        "-c:v", "libx264", "-crf", "20", "-preset", "medium",
        "-pix_fmt", "yuv420p",
        args.output,
    ]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE,
                            stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    for i in range(target_len):
        combined = compose_frame(rrt_frames[i], opt_frames[i], i)
        proc.stdin.write(np.asarray(combined).tobytes())
    proc.stdin.close()
    proc.wait()

    if proc.returncode != 0:
        print(f"ffmpeg error: {proc.stderr.read().decode()[:500]}")
        sys.exit(1)

    dur = target_len / FPS
    print(f"Wrote {args.output} ({target_len} frames, {dur:.1f}s)")


if __name__ == "__main__":
    main()
